version: '3'
services:
  moviesdb:
    image: "postgres:12"
    environment:
      POSTGRES_USER: movies_admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: movies
    ports:
      - "5433:5432"
    volumes:
      - "postgres-data: /var/lib/postgresql/data"
  backend:
    build:
      context: .
    command: sh -c "python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    depends_on:
      - moviesdb
volumes:
  postgres-data:
